/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
 * Generated on: 24-Mar-2022 09:23:32
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 2
 * Stable              : Yes
 * Linear Phase        : No
 * Arithmetic          : single
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2021b\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 5
const int NL[MWSPT_NSEC] = { 1,3,1,3,1 };
const real32_T NUM[MWSPT_NSEC][3] = {
  {
     0.9355121851,              0,              0 
  },
  {
                1,   0.6207890511,              1 
  },
  {
     0.9355121851,              0,              0 
  },
  {
                1,   0.6207890511,              1 
  },
  {
                1,              0,              0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1 };
const real32_T DEN[MWSPT_NSEC][3] = {
  {
                1,              0,              0 
  },
  {
                1,   0.6996148825,   0.8777751923 
  },
  {
                1,              0,              0 
  },
  {
                1,    0.459623605,   0.8726683259 
  },
  {
                1,              0,              0 
  }
};
